version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: hypo-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  relay:
    build: .
    container_name: hypo-relay
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=info
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - REDIS_URL=redis://redis:6379
      - RATE_LIMIT_PER_MIN=100
      - MAX_CONNECTIONS=1000
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

volumes:
  redis-data:

